//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerDetail()
        {
            this.CustomerAddressDetails = new HashSet<CustomerAddressDetail>();
            this.CustomerBankDetails = new HashSet<CustomerBankDetail>();
            this.CustomerLoanDetails = new HashSet<CustomerLoanDetail>();
        }
    
        public System.Guid CustomerId { get; set; }
        public string Customername { get; set; }
        public string PanNo { get; set; }
        public string AadhaarNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.Guid> LedgerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddressDetail> CustomerAddressDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBankDetail> CustomerBankDetails { get; set; }
        public virtual Ledger Ledger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerLoanDetail> CustomerLoanDetails { get; set; }
    }
}
