//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLoanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerLoanDetail()
        {
            this.CustomerLoanEMIs = new HashSet<CustomerLoanEMI>();
        }
    
        public System.Guid LoanId { get; set; }
        public string SocietyLoanSlNo { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid CustomerId { get; set; }
        public double SanctionedAmount { get; set; }
        public double RateOfInterest { get; set; }
        public double EMIPrincipalAmount { get; set; }
        public double EMIInterestAmount { get; set; }
        public Nullable<double> ShareAmount { get; set; }
        public Nullable<double> ROIShare { get; set; }
        public Nullable<double> InsuranceAmount { get; set; }
        public Nullable<double> PaidInsuranceFromSociety { get; set; }
        public Nullable<double> PayableAmount { get; set; }
        public long NoOfEMI { get; set; }
        public string LoanTypeName { get; set; }
        public string LoanSubTypeName { get; set; }
        public string EMIPeriodFormate { get; set; }
        public Nullable<int> EMIPeriod { get; set; }
        public int EMIPaidDay { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCompoundInterest { get; set; }
        public string Transection_Ref_No { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual SocietyLoanDetail SocietyLoanDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerLoanEMI> CustomerLoanEMIs { get; set; }
    }
}
