//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddressDetail
    {
        public long Id { get; set; }
        public System.Guid CustomerId { get; set; }
        public string PrVill { get; set; }
        public string PrPS { get; set; }
        public string PrPIN { get; set; }
        public string prDist { get; set; }
        public string pmVill { get; set; }
        public string pmPS { get; set; }
        public string pmPIN { get; set; }
        public string pmDist { get; set; }
        public string mNo { get; set; }
        public string lNo { get; set; }
        public string emailID { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
    }
}
