//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ledger()
        {
            this.CustomerDetails = new HashSet<CustomerDetail>();
            this.LedgerBankDetails = new HashSet<LedgerBankDetail>();
            this.LedgersStatus = new HashSet<LedgersStatu>();
        }
    
        public long Id { get; set; }
        public System.Guid LedgerId { get; set; }
        public string LedgerName { get; set; }
        public string TemplateName { get; set; }
        public string Category { get; set; }
        public string SubAccount { get; set; }
        public Nullable<System.Guid> ParentLedgerId { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsFixed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDetail> CustomerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedgerBankDetail> LedgerBankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedgersStatu> LedgersStatus { get; set; }
    }
}
