//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSubType
    {
        public long Id { get; set; }
        public string SubTypeName { get; set; }
        public Nullable<long> LoanTypeId { get; set; }
        public Nullable<double> MaxLoanAmount { get; set; }
        public Nullable<double> MinLoanAmount { get; set; }
        public string EMIPeriodFormate { get; set; }
        public Nullable<int> EMIPeriod { get; set; }
        public Nullable<bool> IsCompoundInterest { get; set; }
    
        public virtual LoanType LoanType { get; set; }
    }
}
