//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyDetail
    {
        public string SocietyName { get; set; }
        public string At { get; set; }
        public string PO { get; set; }
        public string Block { get; set; }
        public string SubDivission { get; set; }
        public string PS { get; set; }
        public string DIST { get; set; }
        public string PIN { get; set; }
        public string ESTD { get; set; }
        public string Category { get; set; }
        public string Ph { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public byte[] Logo { get; set; }
        public string GP { get; set; }
        public string CentreCode { get; set; }
        public string Area { get; set; }
        public string DistrictCode { get; set; }
        public string RegistrationNo { get; set; }
        public string GSTNo { get; set; }
        public string PanNo { get; set; }
    }
}
