//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyLoanDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SocietyLoanDetail()
        {
            this.CustomerLoanDetails = new HashSet<CustomerLoanDetail>();
            this.SocietyLoanEMIs = new HashSet<SocietyLoanEMI>();
        }
    
        public long id { get; set; }
        public string SocietyLoanSlNo { get; set; }
        public double SanctionedAmount { get; set; }
        public System.DateTime Date { get; set; }
        public double RateOfInterest { get; set; }
        public double EMIPrincipalAmount { get; set; }
        public double EMIInterestAmount { get; set; }
        public double PayableAmount { get; set; }
        public long NoOfEMI { get; set; }
        public string LoanTypeName { get; set; }
        public string LoanSubTypeName { get; set; }
        public string EMIPeriodFormate { get; set; }
        public int EMIPeriod { get; set; }
        public int EMIPaidDay { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsCompoundInterest { get; set; }
        public System.Guid LedgerFrom { get; set; }
        public System.Guid LedgerTo { get; set; }
        public string Transection_Ref_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerLoanDetail> CustomerLoanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocietyLoanEMI> SocietyLoanEMIs { get; set; }
    }
}
