//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transection
    {
        public long id { get; set; }
        public System.Guid TransectionID { get; set; }
        public System.DateTime Date { get; set; }
        public string No { get; set; }
        public string TransectionType { get; set; }
        public System.Guid LedgerIdFrom { get; set; }
        public System.Guid LedgerIdTo { get; set; }
        public Nullable<double> Amount_Dr { get; set; }
        public Nullable<double> Amount_Cr { get; set; }
        public string Mode { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Narration { get; set; }
        public string Status { get; set; }
        public string Transection_Ref_No { get; set; }
    }
}
